[package]
name = "csvgen"
version = "0.1.2"
authors = ["sashakm <sashakm@bricknet.de>"]
description = "small utility to create mock-csvfiles."
license = "BSD-3-Clause"
repository = "https://github.com/sashakm/csvgen"
readme = "README.md"

[dependencies]
clap = "4.5.54"
rand = "0.9.2"
