[package]
name = "csvgen"
version = "0.1.1"
authors = ["joppich <joppich@bricknet.de>"]
description = "small utility to create mock-csvfiles."
license = "BSD-3-Clause"
repository = "https://github.com/joppich/csvgen"
readme = "README.md"

[dependencies]
clap = "2.33.3"
rand = "0.8.4"